name: caller workflow
on: 
 workflow_dispatch:
  inputs: 
   target-file:
        description: 'target file we overwrite with corresponding environment secrets'
        required: false
        type: string
 # push: 
 #   branches: ["master"]
   
permissions:
  id-token: write
  contents: read
jobs:
  JsonTranform:
    uses: MohithPilli/DonetApp/.github/workflows/test.yml@master
    with: 
     target-file: ''
    secrets: 
     secrets-json: ${{ toJson(secrets) }}
