name:  workflow
on: 
 push: 
  branches: ["master"]

jobs:
  
  Build:  
    runs-on: ubuntu-latest

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: transform settings.json
      run: |
        jq -n --argfile base settings.json --argfile env dev.settings.json 'reduce ($base | to_entries + $env | to_entries)[] as $item ({}; .[$item.key] = $item.value)' > settings.json
      shell: bash

    - name: show settings.json
      run: cat settings.json
      