name:  workflow
on: 
 push: 
  branches: ["master"]

jobs:
  
  Build:  
    runs-on: ubuntu-latest

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: show settings.json
      run: cat settings.json
      shell: bash

       # Step 3: Update JSON File with Secrets Dynamically
    - name: Update JSON File with Secrets
      env:
       key1: ${{ secrets.KEY1 }}
       key2: ${{ secrets.KEY2 }}
      run: |
         JSON_FILE="./settings.json"
         KEYS=$(jq -r 'keys[]' $JSON_FILE)
         for KEY in $KEYS; do
           SECRET_VALUE=$(printenv "$KEY")
           jq --arg key "$KEY" --arg value "$SECRET_VALUE" '.[$key] = $value' $JSON_FILE > temp.json && mv temp.json settings.json
         done
         cat settings.json
      shell: bash     
