name:  workflow
on: 
 push: 
  branches: ["master"]

jobs:
  
  Build:  
    runs-on: ubuntu-latest

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: show settings.json
      run: cat settings.json
      shell: bash

       # Step 3: Update JSON File with Secrets Dynamically
    - name: Update JSON File with Secrets
      run: |
         # Read all keys from the JSON file
         KEYS=$(jq -r 'keys[]' $settings.json)
         # Iterate over the keys and update their values from GitHub secrets
         for KEY in $KEYS; do
           SECRET_VALUE="${{ secrets[KEY] }}"
           if [[ -n "$SECRET_VALUE" ]]; then
             jq --arg key "$KEY" --arg value "$SECRET_VALUE" \
               '.[$key] = $value' $JSON_FILE > temp.json && mv temp.json $settings.json
           fi
         done
         # Print the updated JSON file for verification
         cat $settings.json
      shell: bash
      
