name:  workflow
on: 
 workflow_call:
  secrets: 
    secrets-json:
     description: 'JSON-formatted secrets'
     required: false
     
  inputs: 
   target-file:
        description: 'target file we overwrite with corresponding environment secrets'
        required: false
        type: string
  

jobs:
  
  Build:  
    runs-on: ubuntu-latest
    environment: dev

    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: show settings.json
      run: cat settings.json
      shell: bash

       # Step 3: Update JSON File with Secrets Dynamically
    - name: Update JSON File with Secrets
      run: |
         # Define the JSON file path
         JSON_FILE="${{ inputs.target-file }}"
         # Read all keys from the JSON file
         echo "Reading keys from JSON file..."
         KEYS=$(jq -r 'keys[]' $JSON_FILE)
         echo "Keys found in JSON file: $KEYS"
         
         # Convert SECRETS_JSON into a readable format
         echo '${{ secrets.secrets-json }}' | jq . > secrets_temp.json
         echo "Available GitHub secrets:"
         cat secrets_temp.json
         
         # Iterate over the keys and update their values from environment variables
         for KEY in $KEYS; do
           echo "Processing key: $KEY"
           SECRET_VALUE=$(jq -r --arg key "$KEY" '.[$key] // empty' secrets_temp.json)
           if [[ -n "$SECRET_VALUE" ]]; then
             echo "Found matching GitHub secret for key: $KEY"
             jq --arg key "$KEY" --arg value "$SECRET_VALUE" \
               '.[$key] = $value' "$JSON_FILE" > temp.json && mv temp.json ${{ inputs.target-file }}
           fi
         done
         # Print the updated JSON file for verification
         echo "Updated JSON file content:"
         cat settings.json
      shell: bash  
